<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ADMIN-PC" ignored="0" name="FirefoxTest" tests="2" failures="1" timestamp="23 Mar 2019 19:42:26 GMT" time="109.642" errors="0">
  <testcase name="verifySignInFunctionality" time="59.483" classname="tests.SignInTest"/>
  <testcase name="verifySignInFunctionality" time="26.432" classname="tests.SignInTest">
    <failure type="java.lang.AssertionError" message="SignInTest test is failed">
      <![CDATA[java.lang.AssertionError: SignInTest test is failed
at utils.ReportingUtil.report(ReportingUtil.java:56)
at page.objects.AccountPage.verifyMyAccountPageIsDisplayed(AccountPage.java:38)
at tests.SignInTest.verifySignInFunctionality(SignInTest.java:54)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- verifySignInFunctionality -->
</testsuite> <!-- FirefoxTest -->
